import 'package:equatable/equatable.dart';

enum AiLevel { basic, standard, advanced }

// Simplified representation of a chart to be generated by AI
class AiChartData {
  final String title;
  final String type; // e.g., 'bar', 'pie', 'line'
  final Map<String, dynamic> data;

  AiChartData({required this.title, required this.type, required this.data});
}

class AiCanvasData extends Equatable {
  final String originalQuery;
  final String? textReport;
  final List<AiChartData> charts;
  final DateTime lastRefreshed;

  const AiCanvasData({
    required this.originalQuery,
    this.textReport,
    this.charts = const [],
    required this.lastRefreshed,
  });

  @override
  List<Object?> get props => [originalQuery, textReport, charts, lastRefreshed];
}

abstract class AiEvent extends Equatable {
  const AiEvent();

  @override
  List<Object?> get props => [];
}

class GenerateAiReport extends AiEvent {
  final String query;
  final AiLevel preferredLevel;

  const GenerateAiReport({required this.query, required this.preferredLevel});

  @override
  List<Object?> get props => [query, preferredLevel];
}

class RefreshLastAiReport extends AiEvent {}

class RequestAiComment extends AiEvent {
  final dynamic data;

  const RequestAiComment({required this.data});

  @override
  List<Object?> get props => [data];
}

