import 'package:equatable/equatable.dart';

enum AiLevel { basic, standard, advanced }

// Simplified representation of a chart to be generated by AI
class AiChartData {
  final String title;
  final String type; // e.g., 'bar', 'pie', 'line', 'table', 'text'
  final String explanation;
  final dynamic data;
  final bool isTransforming;

  AiChartData({
    required this.title, 
    required this.type, 
    this.explanation = '', 
    required this.data,
    this.isTransforming = false,
  });

  AiChartData copyWith({
    String? title,
    String? type,
    String? explanation,
    dynamic data,
    bool? isTransforming,
  }) {
    return AiChartData(
      title: title ?? this.title,
      type: type ?? this.type,
      explanation: explanation ?? this.explanation,
      data: data ?? this.data,
      isTransforming: isTransforming ?? this.isTransforming,
    );
  }
}

class AiCanvasData extends Equatable {
  final String originalQuery;
  final String? textReport;
  final List<AiChartData> charts;
  final DateTime lastRefreshed;

  const AiCanvasData({
    required this.originalQuery,
    this.textReport,
    this.charts = const [],
    required this.lastRefreshed,
  });

  @override
  List<Object?> get props => [originalQuery, textReport, charts, lastRefreshed];
}

abstract class AiEvent extends Equatable {
  const AiEvent();

  @override
  List<Object?> get props => [];
}

class GenerateAiReport extends AiEvent {
  final String query;
  final String contextData;
  final AiLevel preferredLevel;

  const GenerateAiReport({
    required this.query,
    required this.contextData,
    required this.preferredLevel,
  });

  @override
  List<Object?> get props => [query, contextData, preferredLevel];
}

class RefreshLastAiReport extends AiEvent {}

class RequestAiComment extends AiEvent {
  final dynamic data;

  const RequestAiComment({required this.data});

  @override
  List<Object?> get props => [data];
}

class RemoveChart extends AiEvent {
  final int index;

  const RemoveChart({required this.index});

  @override
  List<Object?> get props => [index];
}

class TransformChart extends AiEvent {
  final int index;
  final String newType;

  const TransformChart({required this.index, required this.newType});

  @override
  List<Object?> get props => [index, newType];
}
