// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJOGuTfPz-Fkd5vmEzDbHqmFrrDfipCAE',
    appId: '1:854994592901:web:8741fbb5e1a2fdd447f5ec',
    messagingSenderId: '854994592901',
    projectId: 'rmss-6fb66',
    authDomain: 'rmss-6fb66.firebaseapp.com',
    storageBucket: 'rmss-6fb66.firebasestorage.app',
    measurementId: 'G-68V3TLFP1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvc__6LcFOCOdlLSwoIwhd0PAQImptOj0',
    appId: '1:854994592901:android:9834449b7471e85547f5ec',
    messagingSenderId: '854994592901',
    projectId: 'rmss-6fb66',
    storageBucket: 'rmss-6fb66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQqVmFXrljoICVdE4P8Q1QB8kkAu5fri0',
    appId: '1:854994592901:ios:836c5688776a515d47f5ec',
    messagingSenderId: '854994592901',
    projectId: 'rmss-6fb66',
    storageBucket: 'rmss-6fb66.firebasestorage.app',
    iosBundleId: 'com.example.rmss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJOGuTfPz-Fkd5vmEzDbHqmFrrDfipCAE',
    appId: '1:854994592901:web:a7e91026e8419c6f47f5ec',
    messagingSenderId: '854994592901',
    projectId: 'rmss-6fb66',
    authDomain: 'rmss-6fb66.firebaseapp.com',
    storageBucket: 'rmss-6fb66.firebasestorage.app',
    measurementId: 'G-YGG25MJGXB',
  );
}
